### ISSUE TITLE
MQTT: implement duplicate-clientId session takeover (will-message + durable-session races, esp. multi-worker)

### ISSUE THREAD

**Issue by kriszyp** [HarperFast/harper#1604]
## Background

Surfaced during review of #1603 (which makes MQTT share its port across workers via `SO_REUSEPORT` on Linux). The concern is **pre-existing** — it is not introduced by #1603 — but multi-worker MQTT makes it materially more reachable, so it's worth tracking.

## Problem

MQTT does not implement duplicate-`clientId` **session takeover**. Per MQTT 3.1.1 §3.1.4, when a client connects with a `ClientId` that already has a live connection, the server MUST disconnect the existing connection first. `getSession()` in `server/DurableSubscriptionsSession.ts` creates/loads the session from the shared `hdb_session*` tables but never disconnects a prior live connection for the same `clientId` (there's no cross-connection/cross-worker registry check).

Consequences, both racing on the shared LMDB tables when a client reconnects (without a clean DISCONNECT) and the old connection is still half-open:

1. **Will-message race** — when the old connection's keepalive finally expires, its `disconnect(false)` publishes the will found in `hdb_session_will` and deletes it. But the *new* connection wrote its own will to the same shared record, so the old worker can publish the currently-connected client's will and delete it.
2. **Durable-session overwrite** — two live `DurableSubscriptionsSession` instances (potentially on different workers) mapped to the same `hdb_session` record can overwrite each other's `startTime` / `subscriptions`.

Single-worker exhibits (1) already; port-sharing across workers widens both because a reconnect can land on a different worker than the prior connection, with no shared in-memory visibility.

## Direction (not yet designed)

Needs a cross-worker view of active `clientId`s (or a takeover signal) so a new connection can evict the prior one before taking over the durable session — likely coordinated through the shared session table + `transactionBroadcast`, rather than the per-worker in-memory `mqttSettings.sessions` set. Retained-message delivery and cross-worker propagation are already handled correctly by the DB layer.

_Filed by Claude (Opus 4.8) as a follow-up to #1603._

**Comment by kriszyp** [comment]
Concrete will-message exhibit of the missing dup-clientId takeover, from exploratory QA (harper `228eacc0f`, 2/2 stable): the per-clientId `hdb_session_will` record is shared with **no connection-identity guard**, so a stale connection's keepalive expiry publishes the LIVE reconnected client's will (wrong-will publish) **and** deletes it (will loss).

Sequence: Client A connects durable `clientId=c1` with will `A-will` (keepalive 2s), A's client-side keepalive pinger is killed (socket stays open but silent = hung client). Client B connects same `clientId=c1` with a different will `B-will` (long keepalive, stays alive).
1. B's connect does not fire A's will (no takeover — consistent with this issue).
2. On B's CONNECT, `hdb_session_will[c1]` is unconditionally overwritten A→B (`getSession()` does a bare `getLastWill().put(will)`, keyed only by clientId — no ownership check).
3. When A's stale connection's **server** keepalive expires, `session.disconnect(false)` on A's session looks up the will by `this.sessionId` (= `c1`, shared with B) → **publishes B's will while B is still fully connected** (wrong-will publish); A's own will never fires (will loss for A); then the row is **deleted** → if B later drops uncleanly, no will can ever fire for B either.

Root: `server/DurableSubscriptionsSession.ts` — `getSession()` (~126-129) and `SubscriptionsSession.disconnect()` (~374-390) key the will/session record by `sessionId` (= clientId) alone. Fix: key will/session state by connection identity (or implement takeover so the old session's will handling doesn't touch the new one).

Repro: local `qa-scratch/qa452-mqtt-will-race.test.ts`.

**Comment by kriszyp** [comment]
Adding the cross-node case, from dispatch QA finding F-308. This issue's existing comment
(2026-07-06) covers the same-node / multi-worker will race; the mechanism below is the cluster-scope
sibling, and it is unchanged on `origin/main`.

**Duplicate MQTT `clientId` across two nodes: no takeover, `hdb_durable_session` LWW-clobbers, one
publish double-delivers, and the clobbered subscription's offline backlog is silently lost — while
CONNACK still reports `sessionPresent: true`.**

Mechanism, all on current main:

- `server/DurableSubscriptionsSession.ts` ~`:135-141` — `getSession()` builds a brand-new
  `DurableSubscriptionsSession` from the `hdb_durable_session` row alone
  (`getDurableSession().get(sessionId, { returnNonexistent: true })`), with no live-connection lookup
  of any kind. So a second CONNECT with an existing `clientId` neither takes over nor rejects.
- `server/mqtt.ts:45` — `mqttSettings.sessions = new Set()`; added to unconditionally at `:372`
  (**after** `getSession()` has resolved and `sessionPresent` was already computed and sent in
  CONNACK), drained at `:269/:444/:594`, and never iterated to evict a same-`clientId` duplicate.
- That `Set` hangs off the thread-local `server`, so it is per-worker — not node-wide, let alone
  cluster-wide. Any eviction/takeover rule needs to cross the replication boundary;
  `transactionBroadcast` alone does not guarantee it.

PR #1697 (merged 2026-07-08, "close last-will persistence race") fixed a write-ordering-vs-CONNACK
race in this file and does not touch the registry/eviction gap.

Filing as a comment rather than a new issue since the takeover-semantics decision is the same one
this issue already needs; happy to split it out if the cluster scope makes it a different fix.

— Claude (Opus 5), dispatch QA finding-triage pass (F-308)
